### ISSUE TITLE
Make ClinSeq unit tests not depend on live db

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1419]
From JIRA CI-157

The following unit tests depend on getting builds from the live db:
Somatic variation builds:
- [x] Model/ClinSeq/Command/CreateMutationDiagrams.t
- [x] Model/ClinSeq/Command/CreateMutationSpectrum-exome.t
- [x] Model/ClinSeq/Command/CreateMutationSpectrum-wgs.t
- [ ] Model/ClinSeq/Command/GenerateClonalityPlots.t
- [ ] Model/ClinSeq/Command/GetBamReadCountsMatrix.t
- [ ] Model/ClinSeq/Command/GetVariantSources.t
- [x] Model/ClinSeq/Command/ImportSnvsIndels.t
- [ ] Model/ClinSeq/Command/RunCnView.t
- [x] Model/ClinSeq/Command/SummarizeSvs.t

Rna-seq builds:
- [ ] Model/ClinSeq/Command/CufflinksDifferentialExpression.t
- [ ] Model/ClinSeq/Command/CufflinksExpressionAbsolute.t
- [ ] Model/ClinSeq/Command/TophatJunctionsAbsolute.t
- [x] Model/ClinSeq/Command/Converge/CufflinksDe.t

SomVar + Rna-Seq:
- [ ] Model/ClinSeq/Command/GetBamReadCounts.t

Clin-seq build:
- [ ] Model/ClinSeq/Command/DumpIgvXml.t
- [ ] Model/ClinSeq/Command/SummarizeBuilds.t
- [x] Model/ClinSeq/Command/SummarizeCnvs.t
- [x] Model/ClinSeq/Command/SummarizeModels.t
- [ ] Model/ClinSeq/Command/Converge/AllEvents.t

Multiple types?
- [ ] Model/ClinSeq/Command/TestGenomeCommands.t
- [ ] Model/ClinSeq/Command/UpdateAnalysis.t

**Comment by jasonwalker80** [comment]
@tmooney when you have time, could you update the task list on this issue for tests that have already been updated to use mock data?

**Comment by tmooney** [comment]
I've ticked the boxes by the ones that I've merged this week.

**Comment by susannasiebert** [comment]
I ticked the box for SummarizeSvs since there is an open PR to fix the failing test.

**Comment by susannasiebert** [comment]
CreateMutationDiagram.t was already ported over to use the test data.

**Comment by susannasiebert** [comment]
A PR for CreateMutationSpectrum-wgs and CreateMutationSpectrum-exome has been created.

**Comment by jasonwalker80** [comment]
@gatoravi  and/or @susannasiebert is the test for `Model/ClinSeq/Command/ImportSnvsIndels.t` still necessary?

**Comment by susannasiebert** [comment]
`ImportSnvsIndels.pm` is still around so I think we should keep the test. If we decide to delete the command altogether, we would also delete the related test. @gatoravi Do you think it's ok to delete this command altogether?

**Comment by gatoravi** [comment]
Is `ImporSnvsIndels.pm` not used at all in the currentl clinseq workflow, we are now completely reliant on the snv-indel-report right? If this is true, I'm ok with removing this. I'd check with @malachig to make sure this is ok.

**Comment by susannasiebert** [comment]
@gatoravi That's correct. ClinSeq now only uses the SnvIndelReport.

**Comment by malachig** [comment]
Yeah if we are fully transitioned to SnvIndelReport then we can drop this module and the associated test.
